"""Add new note columns

Revision ID: 81c86fb83ba5
Revises: 400271457b52
Create Date: 2026-06-01 21:08:07.118361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81c86fb83ba5'
down_revision: Union[str, Sequence[str], None] = '400271457b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('ai_summary', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('ai_tags', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'ai_tags')
    op.drop_column('notes', 'ai_summary')
    # ### end Alembic commands ###
